### ISSUE TITLE
Добавление метки времени

### ISSUE THREAD

**Issue by BulgArNik** [AntoineLarine/NetWinapiCms#2]
Подскажите, пожалуйста, а как реализовать добавление TimeStamp, дабы установить метку времени в подпись?

**Comment by LarinLive** [comment]
В ближайшие дни сделаю примеры и статью

**Comment by BulgArNik** [comment]
Это будет невероятно полезно для меня. Огромное спасибо!

**Comment by LarinLive** [comment]
Статья готова https://habr.com/ru/articles/771162, примеры кода обновлены коммитом 27cc9faaf767998b881d8d89407bc2388b55a7d9.
