### ISSUE TITLE
Ошибка "Неизвестный криптографический алгоритм"

### ISSUE THREAD

**Issue by NetworKKnighT** [AntoineLarine/NetWinapiCms#3]
Установлен Крипто Про 4,0.

При попытке выполнить подпись получаю ошибку "Неизвестный криптографический алгоритм.". Ошибка происходит при вызове функции CryptMsgOpenToEncode.

Предполагаю, что неправильно устанавливается oid в строчке:
`Encoding.ASCII.GetBytes(pin, new Span<byte>(digestOidRaw, digestOidLength));`

Но даже с учетом исправления этой ошибки, все равно получаю "Неизвестный криптографический алгоритм".

При попытке выполнить проверку подписи получаю ошибку "Параметр задан неверно." при вызове функции CryptMsgControl.

**Comment by LarinLive** [comment]
Поправил копипасту, пробуйте. Какой OID вы передаёте?

**Comment by NetworKKnighT** [comment]
Пробую как у вас в примере:
```c#
var data = Encoding.UTF8.GetBytes("Test");
var digestOid = GostOids.id_tc26_gost3410_12_256;
var signedCms = CmsHelper.Sign(data, true, cert, digestOid, true, "");
```

**Comment by LarinLive** [comment]
В сертификате какая длина ключа: 256 или 512?

**Comment by NetworKKnighT** [comment]
В сертификате длина ключа 256.
Установил `var digestOid =id_tc26_gost3411_12_256;` сработало без ошибок.
Но при проверке все так же "Параметр задан неверно."

**Comment by LarinLive** [comment]
Да, тут тоже поторопился, вставил не тот OID. Алгоритм хэширования должен соответствовать алгоритму в сертификате (особенность именно ГОСТ). Можно так задавать:

```cs
Oid digestOid;
if (certificate.PublicKey.Oid.Value == GostOids.id_tc26_gost3410_12_256.Value)
	digestOid = GostOids.id_tc26_gost3411_12_256;
else if (certificate.PublicKey.Oid.Value == GostOids.id_tc26_gost3410_12_512.Value)
	digestOid = GostOids.id_tc26_gost3411_12_512;
else
	digestOid = OiwOids.id_sha1; // или что-то иное, или ошибка
```

**Comment by LarinLive** [comment]
> Но при проверке все так же "Параметр задан неверно."

Проверяете эту же подпись? Или другую?

**Comment by NetworKKnighT** [comment]
Сначала пробовал другую, теперь эту же, результат одинаковый

**Comment by LarinLive** [comment]
Подпись проходит проверку в [этом](https://www.gosuslugi.ru/help/faq/state_key/55504) сервисе?

**Comment by LarinLive** [comment]
Если имя владельца сертификата не является тайной, то приложите файл с произвольными пробными исходными данными и файл подписи, посмотрю.

**Comment by NetworKKnighT** [comment]
> Подпись проходит проверку в [этом](https://www.gosuslugi.ru/help/faq/state_key/55504) сервисе?

Обе подписи, которые я пытаюсь проверить, проходят проверку

**Comment by NetworKKnighT** [comment]
> Если имя владельца сертификата не является тайной, то приложите файл с произвольными пробными исходными данными и файл подписи, посмотрю.

[test.zip](https://github.com/AntoineLarine/NetWinapiCms/files/13296944/test.zip)

**Comment by NetworKKnighT** [comment]
Видимо у меня какая-то локальная проблема, т.к. сейчас попробовал выполнить старый рабочий код, написанный под .Net Framework, он выдает такую же ошибку.

**Comment by LarinLive** [comment]
Скорее всего, проблема в самом CryptoPro. По возможности, надо его обновить и их библиотеку cades. Потому что у меня ваша подпись проверяется успешно и кодом, и программой КриптоАРМ, и тестовой утилитой CryptoPro:

```powershell
PS C:\Program Files\Crypto Pro\CSP> .\csptest.exe -sfsign -verify -in c:\Temp\1\test.data -detached -signature c:\Temp\1\test.data.sig
E:\branches\CSP_5_0r3r\branches\CSP_5_0r3r_0\CSP\samples\csptest\signtsf.c:700:No user cert specified. Cryptocontext will be opened automaticaly.
Error 0x0:
Detached Signature was verified OK
Total: SYS: 0,000 sec USR: 0,000 sec UTC: 0,029 sec
[ErrorCode: 0x00000000]
```

Вот тут проверьте, не требует ли он перехешировать свои файлы.
![image](https://github.com/AntoineLarine/NetWinapiCms/assets/18666703/c77a50a6-da2e-4204-a20f-ff7b99afc98d)

**Comment by NetworKKnighT** [comment]
Да, действительно, проблема была в КриптоПро, выполнил восстановление КриптоПро и перезагрузился.
Теперь проверка подписи выполняется успешно.
Спасибо за помощь!
